### PR TITLE
fix refs to moved packages

### PR DESCRIPTION
**Pull request by ChanceNCounter**
I haven't checked hashes, assuming they should be the same.

### CODE REVIEW

**Comment by JarbasAl** [comment]
the packages were renamed from jarbas_XXX to ovos_XXX

**Comment by ChanceNCounter** [comment]
That's weird, the links resolved...

**Comment by ChanceNCounter** [comment]
That may or may not have done it.

**Comment by j1nx** [comment]
Looks good, seems you guys are getting the hang of it ;)

**Comment by NeonDaniel** [comment]
> That's weird, the links resolved...

For github, old repo links resolve until a new repo is added with the old name (or Github feels like changing that policy I suppose).
@JarbasAl the jarbas plugins are still on PyPI; do you want to add some depreciation notice or pull those?

**Comment by JarbasAl** [comment]
yes, i will push a dummy update with a deprecation warnings and just import the actual plugin, the old packages become an alias at that point essentially. like bs4 for beautifulsoup

**Pull request merged**
